adjust order of deletion
among csi-driver and k8s-addons

diff --git a/tks-cluster/remove-usercluster-wftpl.yaml b/tks-cluster/remove-usercluster-wftpl.yaml
--- a/tks-cluster/remove-usercluster-wftpl.yaml
+++ b/tks-cluster/remove-usercluster-wftpl.yaml
@@ -24,21 +24,31 @@ spec:
   templates:
   - name: main
     steps:
-    - - name: deleteAddonsApp
-        templateRef:
-          name: delete-apps
-          template: DeleteAppsByName
-        arguments:
-          parameters:
-            - app_name: "{{workflow.parameters.app_prefix}}-kubernetes-addons"
-
     - - name: deleteCsiDriverApp
         templateRef:
           name: delete-apps
           template: DeleteAppsByName
         arguments:
           parameters:
-            - app_name: "{{workflow.parameters.app_prefix}}-aws-ebs-csi-driver"
+            - name: app_name
+              value: "{{workflow.parameters.app_prefix}}-aws-ebs-csi-driver"
+
+    - - name: deleteCalicoController
+        template: deleteCalicoController
+        arguments:
+          parameters:
+            - name: target_namespace
+              value: "kube-system"
+
+    - - name: deleteAddonsApp
+        templateRef:
+          name: delete-apps
+          template: DeleteAppsByName
+        arguments:
+          parameters:
+            - name: app_name
+              value: "{{workflow.parameters.app_prefix}}-kubernetes-addons"
+
 
     - - name: disableAutoSyncOfClusterApp
         template: disableAutoSync
@@ -105,6 +115,36 @@ spec:
       envFrom:
         - secretRef:
             name: "decapod-argocd-config"
+
+  - name: deleteCalicoController
+    arguments: {}
+    inputs:
+      parameters:
+        - name: target_namespace
+    container:
+      name: delete-calico
+      image: 'k8s.gcr.io/hyperkube:v1.18.6'
+      command:
+        - /bin/bash
+        - '-c'
+        - |
+          kube_secret=$(kubectl get secret -n {{workflow.parameters.cluster_id}} {{workflow.parameters.cluster_id}}-kubeconfig -o jsonpath="{.data.value}" | base64 -d)
+          echo -e "kube_secret:\n$kube_secret" | head -n 5
+          cat <<< "$kube_secret" > /etc/kubeconfig
+
+          kube_params+="--kubeconfig=/etc/kubeconfig"
+
+          kubectl $kube_params get deployment -n ${TARGET_NAMESPACE} | grep calico-kube-controller
+          if [[ $? =~ 0 ]]; then
+            kubectl $kube_params delete deployment calico-kube-controllers -n ${TARGET_NAMESPACE}
+
+          else
+            echo "Error: deployment 'calico-kube-controllers' was NOT found."
+            exit 1
+          fi
+      env:
+        - name: TARGET_NAMESPACE
+          value: "{{inputs.parameters.target_namespace}}"
 
   - name: deleteClusterCR
     arguments: {}
