get actual thanos-sc endpoint from k8s svc resource

diff --git a/deploy_apps/tks-lma-federation-wftpl.yaml b/deploy_apps/tks-lma-federation-wftpl.yaml
--- a/deploy_apps/tks-lma-federation-wftpl.yaml
+++ b/deploy_apps/tks-lma-federation-wftpl.yaml
@@ -47,15 +47,21 @@ spec:
           name: lma-federation
           template: deploy
 
+    - - name: GetMyThanosScEndpoint
+        template: GetMyThanosScEndpoint
+        arguments:
+          parameters:
+          - name: target_namespace
+            value: lma
+
     - - name: updateEndpointToTksInfo
         templateRef:
           name: update-tks-app-group-info
           template: updateTksAppGroup
         arguments:
           parameters:
-          # TODO: Can this be pre-determined? Or composed dynamically on deployment?
           - name: endpoints
-            value: "{'PROMETHEUS': '{{workflow.parameters.cluster_id}}-thanos-ep'}"
+            value: "{'PROMETHEUS': '{{steps.GetMyThanosScEndpoint.outputs.parameters.my_thanos_sc_ep}}'}"
 
       # LMA appGroup specific task #
     - - name: collectThanosScEndpoints
@@ -69,9 +75,8 @@ spec:
             value: "{{ workflow.parameters.cluster_id }}"
           - name: app_group_id
             value: "{{ workflow.parameters.app_group_id }}"
-          # Again, how can this be determined?
           - name: cur_endpoint
-            value: "{{workflow.parameters.cluster_id}}-thanos-ep"
+            value: "{{steps.GetMyThanosScEndpoint.outputs.parameters.my_thanos_sc_ep}}"
 
     - - name: updateDecapodManifestOutwards
         templateRef:
@@ -154,6 +159,47 @@ spec:
     activeDeadlineSeconds: 900
     retryStrategy:
       limit: 2
+
+  - name: GetMyThanosScEndpoint
+    inputs:
+      parameters:
+      - name: target_namespace
+    outputs:
+      parameters:
+      - name: my_thanos_sc_ep
+        valueFrom:
+          path: /mnt/out/thanos_sc_ep.txt
+    volumes:
+    - name: out
+      emptyDir: {}
+    container:
+      name: 'get-thanos-ep'
+      image: 'k8s.gcr.io/hyperkube:v1.18.6'
+      envFrom:
+      - secretRef:
+          name: "github-tks-mgmt-token"
+      env:
+        - name: TARGET_NAMESPACE
+          value: '{{inputs.parameters.target_namespace}}'
+      volumeMounts:
+      - name: out
+        mountPath: /mnt/out
+      command:
+        - /bin/bash
+        - '-c'
+        - |
+          kube_secret=$(kubectl get secret -n {{workflow.parameters.cluster_id}} {{workflow.parameters.cluster_id}}-kubeconfig -o jsonpath="{.data.value}" | base64 -d)
+          echo -e "kube_secret:\n$kube_secret" | head -n 5
+          cat <<< "$kube_secret" > /etc/kubeconfig
+
+          thanos_sc_ep=$(kubectl --kubeconfig=/etc/kubeconfig get svc THANOS_SC_SVC -n ${TARGET_NAMESPACE} -o jsonpath='{.spec.externalIP}')
+          if [[ -z "$thanos_sc_ep" ]]; then
+            echo "Error: could not retrieve thanos sidecar endpoint from service resource."
+            exit 1
+          else
+            echo $thanos_sc_ep > /mnt/out/thanos_sc_ep.txt
+          fi
+
 
   - name: collectThanosScEndpoints
     inputs:
