support gatekeeper for jaeger sso

diff --git a/deploy_apps/tks-service-mesh-wftpl.yaml b/deploy_apps/tks-service-mesh-wftpl.yaml
--- a/deploy_apps/tks-service-mesh-wftpl.yaml
+++ b/deploy_apps/tks-service-mesh-wftpl.yaml
@@ -47,7 +47,7 @@ spec:
         templateRef:
           name: service-mesh
           template: deploy-start
-    - - name: create-keycloak-client
+    - - name: kiali-create-keycloak-client
         templateRef:
           name: keycloak-client
           template: create-client
@@ -63,7 +63,7 @@ spec:
               value: "keycloak"
             - name: keycloak_credential_secret_namespace
               value: "keycloak"
-    - - name: update-keycloak-client-secret
+    - - name: kiali-update-keycloak-client-secret
         templateRef:
           name: keycloak-client
           template: update-client-secret
@@ -79,13 +79,8 @@ spec:
               value: "keycloak"
             - name: keycloak_credential_secret_namespace
               value: "keycloak"
-            - name: client_role_name
-              value: admin
-            - name: client_secret_enabled
-              value: 'true'
-            - name: client_secret_value
-              value: ""
-    - - name: get-keycloak-client-secret
+
+    - - name: kiali-get-keycloak-client-secret
         templateRef:
           name: keycloak-client
           template: get-client-secret
@@ -105,21 +100,17 @@ spec:
               value: 'true'
             - name: client_secret_value
               value: ""
-    - - name: update-kiali-oidc-git
-        template: update-kiali-oidc-git
+    - - name: kiali-update-oidc-git
+        template: kiali-update-oidc-git
         arguments:
           parameters:
-            - name: client_id
-              value: "{{ workflow.parameters.cluster_id }}-kiali"
-            - name: client_secret
-              value: "{{steps.get-keycloak-client-secret.outputs.parameters.client-secret}}"
             - name: cluster_id
               value: "{{workflow.parameters.cluster_id}}"
             - name: keycloak_url
               value: "{{workflow.parameters.keycloak_url}}"
             - name: organization_id
               value: "{{workflow.parameters.organization_id}}"
-    - - name: create-keycloak-secret-to-k8s-cluster
+    - - name: kiali-create-keycloak-secret-to-k8s-cluster
         template: update-kiali-oidc-git
         arguments:
           parameters:
@@ -127,13 +118,13 @@ spec:
               value: "{{steps.get-keycloak-client-secret.outputs.parameters.client-secret}}"
             - name: cluster_id
               value: "{{workflow.parameters.cluster_id}}"
-    - - name: get-kiali-ep
-        template: get-kiali-ep
+    - - name: kiali-get-ep
+        template: kiali-get-ep
         arguments:
           parameters:
             - name: cluster_id
               value: "{{workflow.parameters.cluster_id}}"
-    - - name: append-client-redirect-uri
+    - - name: kiali-append-client-redirect-uri
         templateRef:
           name: keycloak-client
           template: append-client-redirect-uri
@@ -150,11 +141,98 @@ spec:
             value: "keycloak"
           - name: redirect_uri
             value: "{{steps.get-kiali-ep.outputs.parameters.kiali_ep}}/*"
-  - name: get-kiali-ep
+    - - name: jaeger-create-keycloak-client
+        templateRef:
+          name: keycloak-client
+          template: create-client
+        arguments:
+          parameters:
+            - name: server_url
+              value: "{{ workflow.parameters.keycloak_url }}"
+            - name: target_realm_name
+              value: "{{ workflow.parameters.organization_id }}"
+            - name: target_client_id
+              value: "{{ workflow.parameters.cluster_id }}-jaeger"
+            - name: keycloak_credential_secret_name
+              value: "keycloak"
+            - name: keycloak_credential_secret_namespace
+              value: "keycloak"
+    - - name: jaeger-update-keycloak-client-secret
+        templateRef:
+          name: keycloak-client
+          template: update-client-secret
+        arguments:
+          parameters:
+            - name: server_url
+              value: "{{ workflow.parameters.keycloak_url }}"
+            - name: target_realm_name
+              value: "{{ workflow.parameters.organization_id }}"
+            - name: target_client_id
+              value: "{{ workflow.parameters.cluster_id }}-jaeger"
+            - name: keycloak_credential_secret_name
+              value: "keycloak"
+            - name: keycloak_credential_secret_namespace
+              value: "keycloak"
+            - name: client_secret_enabled
+              value: 'true'
+            - name: client_secret_value
+              value: ""
+    - - name: jaeger-get-keycloak-client-secret
+        templateRef:
+          name: keycloak-client
+          template: get-client-secret
+        arguments:
+          parameters:
+            - name: server_url
+              value: "{{ workflow.parameters.keycloak_url }}"
+            - name: target_realm_name
+              value: "{{ workflow.parameters.organization_id }}"
+            - name: target_client_id
+              value: "{{ workflow.parameters.cluster_id }}-jaeger"
+            - name: keycloak_credential_secret_name
+              value: "keycloak"
+            - name: keycloak_credential_secret_namespace
+              value: "keycloak"
+    - - name: jaeger-update-oidc-git
+        template: jaeger-update-oidc-git
+        arguments:
+          parameters:
+            - name: client_secret
+              value: "{{steps.get-keycloak-client-secret.outputs.parameters.client-secret}}"
+            - name: cluster_id
+              value: "{{workflow.parameters.cluster_id}}"
+            - name: keycloak_url
+              value: "{{workflow.parameters.keycloak_url}}"
+            - name: organization_id
+              value: "{{workflow.parameters.organization_id}}"
+    - - name: jaeger-get-ep
+        template: jaeger-get-ep
+        arguments:
+          parameters:
+            - name: cluster_id
+              value: "{{workflow.parameters.cluster_id}}"
+    - - name: jaeger-append-client-redirect-uri
+        templateRef:
+          name: keycloak-client
+          template: append-client-redirect-uri
+        arguments:
+          - name: server_url
+            value: "{{ workflow.parameters.keycloak_url }}"
+          - name: target_realm_name
+            value: "{{ workflow.parameters.organization_id }}"
+          - name: target_client_id
+            value: "{{ workflow.parameters.cluster_id }}-jaeger"
+          - name: keycloak_credential_secret_name
+            value: "keycloak"
+          - name: keycloak_credential_secret_namespace
+            value: "keycloak"
+          - name: redirect_uri
+            value: "{{steps.get-jaeger-ep.outputs.parameters.jaeger_ep}}/*"
+
+  - name: kiali-get-ep
     inputs:
       parameters:
         - name: cluster_id
-        - name: organization_id
     outputs:
       parameters:
         - name: kiali_ep
@@ -177,7 +255,6 @@ spec:
             echo "[$date] $level     $msg"
           }
 
-          organization_id={{inputs.parameters.organization_id}}
           cluster_id={{inputs.parameters.cluster_id}}
 
           #################
@@ -218,12 +295,11 @@ spec:
         - name: out
           mountPath: /mnt/out
 
-  - name: update-kiali-oidc-git
+  - name: kiali-update-oidc-git
     inputs:
       parameters:
-        - name: client_id
-        - name: client_secret
         - name: cluster_id
+        - name: keycloak_url
         - name: organization_id
     container:
       name: update-kiali-resource-git
@@ -239,10 +315,9 @@ spec:
             echo "[$date] $level     $msg"
           }
           
-          client_id={{inputs.parameters.client_id}}
-          organization_id={{workflow.parameters.organization_id}}
-          keycloak_url={{workflow.parameters.keycloak_url}}
           cluster_id={{inputs.parameters.cluster_id}}
+          keycloak_url={{workflow.parameters.keycloak_url}}
+          organization_id={{workflow.parameters.organization_id}}
 
           #################
           # updates
@@ -260,7 +335,7 @@ spec:
           cd ${cluster_id}
 
           # Update kiali client secret
-          yq -i e  ".global.keycloakClientId=\"${client_id}\"" ${cluster_id}/service-mesh/site-values.yaml
+          yq -i e  ".global.keycloakClientPrefix=\"${client_id}\"" ${cluster_id}/service-mesh/site-values.yaml
           yq -i e  ".global.keycloakIssuerUri=\"https://${keycloak_url}/auth/realms/${organization_id}\"" ${cluster_id}/service-mesh/site-values.yaml
 
           git config --global user.name "tks"
@@ -270,6 +345,131 @@ spec:
           cmessage="changes kiali global value for keycloak"
           git add ${cluster_id}/service-mesh/site-values.yaml
           git commit -m "change values on kiali-resource." -m "$cmessage"
+          git push
+
+      envFrom:
+        - secretRef:
+            name: "git-svc-token"
+
+  - name: jaeger-get-ep
+    inputs:
+      parameters:
+        - name: cluster_id
+    outputs:
+      parameters:
+        - name: jaeger_ep
+          valueFrom:
+            path: /mnt/out/jaeger_ep.txt
+    volumes:
+      - name: out
+        emptyDir: { }
+    container:
+      name: get-jaeger-ep
+      image: 'harbor.taco-cat.xyz/tks/shyaml_jq_yq_kubectl_python:3.11'
+      command:
+        - /bin/bash
+        - '-c'
+        - |
+          function log() {
+            level=$1
+            msg=$2
+            date=$(date '+%F %H:%M:%S')
+            echo "[$date] $level     $msg"
+          }
+
+          cluster_id={{inputs.parameters.cluster_id}}
+
+          #################
+          # Get endpoints
+          #################
+          kube_secret=$(kubectl get secret -n ${cluster_id} ${cluster_id}-tks-kubeconfig -o jsonpath="{.data.value}" | base64 -d)
+          cat <<< "$kube_secret" > kubeconfig
+
+          while ! kubectl --kubeconfig=kubeconfig get svc -n tks-msa jaeger --ignore-not-found; do
+            echo "Waiting for the jaeger service to appear in cluster ${cluster_id} (5s)"
+            sleep 5
+          done
+
+          jaeger_ep_secret=$(kubectl get secret -n ${cluster_id} tks-endpoint-secret -o jsonpath='{.data.jaeger}'| base64 -d )
+
+          if [ jaeger_ep_secret == "" ]; then
+            while [ -z $(kubectl --kubeconfig=kubeconfig get svc -n tks-msa jaeger -o jsonpath="{.status.loadBalancer.ingress[*].hostname}") ]; do
+              if [ "$(kubectl --kubeconfig=kubeconfig get svc -n tks-msa jaeger -o jsonpath='{.spec.type}')" != "LoadBalancer" ]; then
+                log "FAIL" "A service for the jaeger in ${cluster_id} is not configured properly.(No LoadBalancer)"
+                exit -1
+              fi
+
+              echo "Waiting for generating the loadbalancer of jaeger(3s)"
+              sleep 3
+            done
+
+            endpoint=$(kubectl --kubeconfig=kubeconfig get svc -n tks-msa jaeger -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
+          else
+            endpoint=${jaeger_ep_secret}
+          fi
+
+          echo ${endpoint} > /mnt/out/jaeger_ep.txt
+
+      envFrom:
+        - secretRef:
+            name: tks-api-secret
+      volumeMounts:
+        - name: out
+          mountPath: /mnt/out
+
+  - name: jaeger-update-oidc-git
+    inputs:
+      parameters:
+        - name: client_secret
+        - name: cluster_id
+        - name: keycloak_url
+        - name: organization_id
+    container:
+      name: update-jaeger-resource-git
+      image: 'harbor.taco-cat.xyz/tks/shyaml_jq_yq_kubectl_python:3.11'
+      command:
+        - /bin/bash
+        - '-c'
+        - |
+          function log() {
+            level=$1
+            msg=$2
+            date=$(date '+%F %H:%M:%S')
+            echo "[$date] $level     $msg"
+          }
+
+          client_secret={{inputs.parameters.client_secret}}
+          cluster_id={{inputs.parameters.cluster_id}}
+          keycloak_url={{workflow.parameters.keycloak_url}}
+          organization_id={{workflow.parameters.organization_id}}
+
+          #################
+          # updates
+          #################
+          GIT_ACCOUNT={{workflow.parameters.github_account}}
+          if  [[ $GIT_SVC_URL == https://* ]]; then
+            repository_base=https://${TOKEN//[$'\t\r\n ']}@${GIT_SVC_URL/http:\/\//}/${GIT_ACCOUNT}/
+          else
+            repository_base=http://${TOKEN//[$'\t\r\n ']}@${GIT_SVC_URL/http:\/\//}/${GIT_ACCOUNT}/
+          fi
+
+          GIT_SVC_HTTP=${GIT_SVC_URL%://*}
+          GIT_SVC_BASE_URL=${GIT_SVC_URL#*//}
+          git clone $GIT_SVC_HTTP://$(echo -n $TOKEN)@${GIT_SVC_BASE_URL}/${USERNAME}/${cluster_id}.git
+          cd ${cluster_id}
+
+          # Update jaeger client secret
+          yq -i e  ".global.keycloakClientPrefix=\"${cluster_id}\"" ${cluster_id}/service-mesh/site-values.yaml
+          yq -i e  ".global.keycloakIssuerUri=\"https://${keycloak_url}/auth/realms/${organization_id}\"" ${cluster_id}/service-mesh/site-values.yaml
+          yq -i e  ".global.gatekeeperSecret=\"${client_secret}\"" ${client_secret}/service-mesh/site-values.yaml
+
+          git config --global user.name "tks"
+          git config --global user.email "tks@sktelecom.com"
+
+          log "INFO" "##### commit changes jaeger resource"
+          cmessage="changes jaeger global value for keycloak"
+          git add ${cluster_id}/service-mesh/site-values.yaml
+          git commit -m "change values on jaeger-resource." -m "$cmessage"
           git push
 
       envFrom:
